### ISSUE TITLE
[BUG] Procedural Cube Seams

### ISSUE THREAD

**Issue by dorythecat** [Dorycraft/VulkanGameEngine#2]
I don't know when did it start, though it was probably around the implementation (fa807f35d1b1b4032dc069656929372801a40803), but the variable-resolution procedural cubes have some seams around the end of the faces.

**Comment by Dorycraft** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement procedural primitives generation](https://trello.com/c/0G2feD0l/3-implement-procedural-primitives-generation)

**Comment by Dorycraft** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Solve Issue #2](https://trello.com/c/HIa9u0pL/33-solve-issue-2)

**Comment by Dorycraft** [comment]
Fixed as of 647fd38ffcd7b60b6d5e416c60a080b24dd5b307.
